# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Research"
  url = ""
  identifier="Research"
  weight = 30

[[main]]
  name = "Research interests"
  url = "/interests"
  parent="Research"
  weight = 31

[[main]]
  name = "Collaborations network"
  url = "/collaborators"
  parent="Research"
  weight = 32

[[main]]
  name = "News"
  url = "/post"
  weight = 20


[[main]]
  name = "Publications"
  url = ""
  identifier="Publications"
  weight = 40

[[main]]
  name = "Peer-reviewed articles"
  url = "/publications"
  parent="Publications"
  weight = 41

[[main]]
  name = "Conferences"
  url = "/conferences"
  parent="Publications"
  weight = 42

[[main]]
  name = "Outreach & media"
  url = "/outreach-media"
  parent="Publications"
  weight = 43

[[main]]
  name = "Download my publication list"
  url = "https://docs.google.com/document/d/1FdBsbgs_0f8w7h_0DU9Xc342jNLIQXdeJMbYajtSHMI/export?format=pdf"
  parent="Publications"
  weight = 44

[[main]]
  name = "Teaching"
  url = "/teaching"
  identifier="Teaching"
  weight = 50

[[main]]
  name = "Data"
  url = ""
  identifier="Data"
  weight = 60

[[main]]
  name = "Datasets"
  url = "/datasets"
  parent="Data"
  weight = 62

[[main]]
  name = "DeepIso - Deep-sea isotope database"
  url = "/deepiso"
  parent="Data"
  weight = 61

[[main]]
  name = "Code"
  url = "/code"
  identifier="Code"
  weight = 80

[[main]]
  name = "CV"
  url = ""
  identifier="CV"
  weight = 80

[[main]]
  name = "Experience"
  url = "/experience"
  parent="CV"
  weight = 81

[[main]]
  name = "Download my CV"
  url = "https://docs.google.com/document/d/1Rzsg8GBgKktObg9NBGtbyBQn94j7zz6sgmjqwWy4Lr4/export?format=pdf"
  parent="CV"
  weight = 82

[[main]]
  name = "Download my publication list"
  url = "https://docs.google.com/document/d/1FdBsbgs_0f8w7h_0DU9Xc342jNLIQXdeJMbYajtSHMI/export?format=pdf"
  parent="CV"
  weight = 83

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90


